language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28
    - sys-img-armeabi-v7a-android-18
notifications:
  email:
    on_success: never
    on_failure: always
    
